name: Setup
on:
  repository_dispatch:
    types: [setup]
jobs:
  fixture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automation here
        run: |
          echo "Call a script to do something .."
          echo "p1 = " ${{ toJson(github.event.client_payload.p1) }}
          echo "p2 = " ${{ toJson(github.event.client_payload.p2) }}
